Use Terraform locals to avoid variable duplication
kinvolk/lokomotive-kubernetes pull request #32
Opened 2019-07-05 16:15 UTC by johananl

I'm opening this PR after multiple times I've made copy-paste mistakes when deploying clusters. I think this can be solved nicely by using [Terraform locals](https://www.terraform.io/docs/configuration/locals.html).

2019-07-05 16:19 UTC, rata approved these changes
LGTM

I was already using locals on my terraform file, didn't realize docs weren't. Good catch! :)

2019-07-09 06:25 UTC, surajssd requested changes

2019-07-09 06:25 UTC, surajssd commented on docs/flatcar-linux/packet.md
> +}
can we also do the same for providers?

2019-07-09 07:28 UTC, indradhanush approved these changes
I've had the same problem. :100: for helping fix it!

LGTM.

2019-07-16 09:30 UTC, invidian approved these changes

2020-01-06 15:00 UTC, invidian commented
@johananl can you please follow up here so we can merge it?

2020-01-09 14:06 UTC, johananl commented on docs/flatcar-linux/packet.md
> +}
Doesn't seem to be possible.

2020-01-09 14:13 UTC, invidian commented on docs/flatcar-linux/packet.md
> +  project_id = "93fake81..."
Should we align those locals here?

2020-01-09 14:19 UTC, merged