Upgrade to Terraform 0.12
kinvolk/lokomotive-kubernetes pull request #45
Opened 2019-07-29 14:50 UTC by johananl

## General

This is a huge PR. It is not ready to be merged yet but I'm opening it in draft mode so that people can start reviewing.

## Testing

To test the PR, install Terraform 0.12 on your machine and create a cluster using the [docs](https://github.com/kinvolk/lokomotive-kubernetes#modules).

The following platforms have been already migrated to Terraform 0.12 and can be tested:

- [ ] AWS
- [ ] Azure
- [ ] Bare metal
- [ ] Packet

## TODO

The following tasks must be completed before merging this PR:

- [ ] Migrate DO, GCP and KVM platforms to Terraform 0.12.
- [ ] Fix whitespace and indentation issues created by `terraform 0.12upgrade`.
- [ ] Finish updating docs.
- [ ] Clean up version requirements.
- [ ] Update CI process to support Terraform 0.12.
- [ ] Merge https://github.com/kinvolk/terraform-render-bootkube/tree/tf12.
- [ ] Pin terraform-render-bootkube module reference to the correct commit.
- [ ] Rebase and squash commits nicely.

2019-07-30 13:06 UTC, invidian requested changes
The suggested changes for Packet provider should also be applied for other providers.

I didn't test it yet.

Also, we need to update the CI as well to support new versions of providers and Terraform.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/workers/variables.tf
> +variable "worker_count" {
This also needs to be updated in examples in documentation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/controllers.tf
> +  user_data = element(
I think this can be simplified to `data.ct_config.controller-install-ignitions[count.index].rendered`.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/controllers.tf
> +  records = [element(packet_device.controllers.*.access_private_ipv4, count.index)]
`packet_device.controllers[count.index].access_private_ipv4`?

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/controllers.tf
> +  content = element(
Ditto array notation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/controllers.tf
> +    postinstall_ignition = element(data.ct_config.controller-ignitions.*.rendered, count.index)
Ditto array notation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/controllers.tf
> +  content = element(
Ditto array notation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/ssh.tf
> +    host    = element(packet_device.controllers.*.access_public_ipv4, count.index)
Ditto array notation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/ssh.tf
> +    node_name = element(packet_device.controllers.*.hostname, count.index)
Ditto array notation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/ssh.tf
> +    node_name = element(var.worker_nodes_hostnames, count.index)
Ditto array notation.

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/ssh.tf
> +    controller_host_endpoints = join(
Can we revert formatting change here?

2019-07-30 13:06 UTC, invidian commented on packet/flatcar-linux/kubernetes/workers/workers.tf
> +  hardware_reservation_id = lookup(
Ditto formatting.

2019-08-01 02:30 UTC, mauriciovasquezbernal commented
Could we use terraform 0.12 types (https://www.terraform.io/docs/configuration/types.html) to avoid problems like https://github.com/kinvolk/lokomotive-kubernetes/pull/44?

2019-08-26 17:51 UTC, johananl commented
>Could we use terraform 0.12 types (https://www.terraform.io/docs/configuration/types.html) to avoid problems like #44?

What change are you suggesting @mauriciovasquezbernal? Could you post an example or even a diff?

2019-08-26 18:18 UTC, johananl commented on packet/flatcar-linux/kubernetes/workers/variables.tf
> +variable "worker_count" {
Oops, done.

2019-08-26 18:24 UTC, johananl commented on packet/flatcar-linux/kubernetes/controllers.tf
> +  user_data = element(
That syntax is invalid.

2019-08-26 20:55 UTC, invidian commented
Will review tomorrow. I was thinking, is there a way to configure Terraform version used for running tests here instead of in CI code? I think this would be good direction to move in the future, so we can make things more self contained.

2019-08-27 07:50 UTC, invidian requested changes
I commented on some nits I would fix, especially formatting in bare-metal module could be improved.

I also think we should merge the PR into bootkube first, then point to the commit from master branch here.

Overall LGMT, great work @johananl.

2019-08-27 07:50 UTC, invidian commented on docs/flatcar-linux/packet.md
> +  version = "~> 2.2.1"
`2.3.0` is available now.

2019-08-27 07:50 UTC, invidian commented on aws/flatcar-linux/kubernetes/require.tf
> +  version = "~> 2.0.1"
`2.1.0` is now available.

2019-08-27 07:50 UTC, invidian commented on packet/flatcar-linux/kubernetes/bootkube.tf
> +  source = "github.com/kinvolk/terraform-render-bootkube?ref=9c1ff5a9e8b3e98922980a097c49c8b3a903437a"
I think updates should cascade, we should merge bootkube PR first, then this one.

2019-08-27 07:50 UTC, invidian commented on packet/flatcar-linux/kubernetes/ssh.tf
> +
I would get rid of those empty lines at the end of every file.

2019-08-27 07:50 UTC, invidian commented on bare-metal/flatcar-linux/kubernetes/groups.tf
> +  name = format(
Formatting changed could/should be reverted here.

2019-08-27 07:50 UTC, invidian commented on bare-metal/flatcar-linux/kubernetes/groups.tf
> +  profile = local.flavor == "flatcar" ? var.cached_install == "true" ? element(
Ditto formatting + please not so many tenary operators! :smile:

2019-08-27 08:16 UTC, invidian commented
> I was thinking, is there a way to configure Terraform version used for running tests here instead of in CI code? I think this would be good direction to move in the future, so we can make things more self contained.

Created kinvolk/PROJECT-Lokomotive-Kubernetes#318 for that.

2019-08-27 09:58 UTC, johananl commented
>I commented on some nits I would fix, especially formatting in bare-metal module could be improved.

@invidian the focus of this PR is **switching to Terraform 0.12**. I think we should stay focused on that and not slip to an overall refactor. I am well aware of the things you've pointed out inline and have spotted most of them myself, I'm just trying to stay focused on switching to the newer Terraform version. For example, I've addressed your previous comment regarding using array notation instead of `element()` - and it took me 2 hours to fix all of these throughout the codebase and test that I didn't break anything. Furthermore, this is a remnant from Typhoon and not something the migration introduced. That said, I think we can fix a few small things but I'd rather not turn this into a full-blown refactor (something we can definitely do in a separate PR *after* the migration).

>I also think we should merge the PR into bootkube first, then point to the commit from master branch here.

It's written as a TODO item in the description.

2019-08-27 10:18 UTC, invidian commented
>@invidian the focus of this PR is switching to Terraform 0.12. I think we should stay focused on that and not slip to an overall refactor. I am well aware of the things you've pointed out inline and have spotted most of them myself, I'm just trying to stay focused on switching to the newer Terraform version. For example, I've addressed your previous comment regarding using array notation instead of element() - and it took me 2 hours to fix all of these throughout the codebase and test that I didn't break anything. Furthermore, this is a remnant from Typhoon and not something the migration introduced. That said, I think we can fix a few small things but I'd rather not turn this into a full-blown refactor (something we can definitely do in a separate PR after the migration).

I understand and accept that some thing might be out of scope for this PR.

I think `element()` thingy should be considered as an improvement, which migration allows us to do, so I would treat it as optional, but it's good that you've made it.

 On the other hand styling is directly caused by the migration (broken tool on Terraform side), so I consider making formatting more inconsistent as an regression here, which shouldn't be introduced. I don't leaving such things as TODO later, because usually it's hard to go back to such things.

>I'd rather not turn this into a full-blown refactor (something we can definitely do in a separate PR after the migration).

If you refer to: `please not so many tenary operators! smile`, I'm sorry for the confusion, I just spotted chained tenary operators and found it funny, I didn't want to suggest, that this should be fixed.

Bottom line is, if you think the patch is working and we should merge it,so we can move forward, and should be improved later, I don't insist on any of my comments.

2019-09-04 02:20 UTC, mauriciovasquezbernal commented
> > Could we use terraform 0.12 types (https://www.terraform.io/docs/configuration/types.html) to avoid problems like #44?
> 
> What change are you suggesting @mauriciovasquezbernal? Could you post an example or even a diff?

AFAIK terraform 0.12 includes a new support for type constraints, we can mark some variables as `number` or `bool`. For instance, `setup_raid` should have `type = bool`, this could avoid problems like  in https://github.com/kinvolk/lokomotive-kubernetes/pull/44 

https://github.com/kinvolk/lokomotive-kubernetes/blob/d454078bd2a61c0624dae65efbf4233c8e17ef7e/packet/flatcar-linux/kubernetes/workers/variables.tf#L102-L106

2019-09-04 14:41 UTC, pothos commented
Please rebase to pick up the CI configuration files.

2019-10-14 09:10 UTC, alvelcom commented
Supporting Terraform v0.12 is a very important thing 👍. Is it still on the table?

2019-10-14 14:34 UTC, rata commented
Yes. But we've been quite slow movinf forward with this :(

2020-01-02 10:19 UTC, invidian commented
I'll close this one. Another attempt in #119.

2020-01-02 10:19 UTC, closed without merging

2020-01-02 10:20 UTC, invidian commented
@johananl please remove the branch if you think it's fine.